# Generated by Django 3.1.3 on 2020-11-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='1', upload_to='product_img'),
            preserve_default=False,
        ),
    ]
