# Generated by Django 3.1.3 on 2020-11-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='product',
            field=models.ManyToManyField(null=True, to='shop.Product'),
        ),
    ]
