# Generated by Django 3.1.3 on 2020-11-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shoppingcart_order_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercard',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='数量'),
        ),
    ]
