# Generated by Django 3.1.3 on 2020-11-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20201117_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='product',
            field=models.ManyToManyField(null=True, related_name='cardorders', to='shop.OrderCard'),
        ),
    ]
