# Generated by Django 3.1.3 on 2020-11-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201117_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
