# Generated by Django 3.1.3 on 2020-11-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_shoppingcart_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_card',
            field=models.ManyToManyField(to='shop.OrderCard'),
        ),
    ]
